<?php
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headMeta() ?>
<?php echo $this->headTitle() ?>  
<link href="<?php echo $this->baseUrl();?>/public/css/reset.css" type="text/css" rel="stylesheet" media="screen"/>

<link href="<?php echo $this->baseUrl();?>/public/css/contact.css" type="text/css" rel="stylesheet" media="screen"/>
<link href="<?php echo $this->baseUrl();?>/public/css/share.css" type="text/css" rel="stylesheet" media="screen"/>
<link href="<?php echo $this->baseUrl();?>/public/css/galledy.css" type="text/css" rel="stylesheet" media="screen"/>
<link href="<?php echo $this->baseUrl();?>/public/css/galledy_exp.css" type="text/css" rel="stylesheet" media="screen"/>
<link href="<?php echo $this->baseUrl();?>/public/css/tab.css" type="text/css" rel="stylesheet" media="screen"/>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/jquery-1.4.4.min.js"></script>
<script>
function woaicssq(num){
for(var id = 1;id<=2;id++ )
{
var MrJin="woaicss_con" +id;
if(id==num)
document.getElementById(MrJin).style.display="block";
else
document.getElementById(MrJin).style.display="none";
}
if(num==1){
document.getElementById("tabmain1").className="tabpic1_hover";
document.getElementById("tabmain2").className="tabpic2";
}
if(num==2){
document.getElementById("tabmain1").className="tabpic1";
document.getElementById("tabmain2").className="tabpic2_hover";
}
}
</script>


</head>

<body>
<div id="container">
  <div id="left"></div>
  <div id="right"> </div>
  <div id="middle">
    <div id="header">
      <div id="tabs">
        <div class="nav">
          <ul>
            <li class="title_home"><a href="<?php echo $this->baseUrl();?>/"></a></li>
            <li class="title_view"><a href="#"></a></li>
            <li class="title_galledy"><a href="#"></a></li>
            <li class="title_department"><a href="#"></a></li>
            <li class="title_contact"><a href="#"></a></li>
          </ul>
        </div>
        <!-- end of nav -->
      </div>
      <!-- end of tabs -->
      <div id="illustrat"></div>
    </div>
    <!-- end of header -->
    
    <div id="contentx">
    	<?php echo $this->layout()->content; ?>
    </div>
    
    <div id="footer"><span>Copyright © 2011-2012 HuaZhong University of Science and Technology Tencent Innovation Club.All rights reserved. Support by Web&Duio</span	> </div>
  </div>
  <!-- end of middle -->
</div>
</html>
