
<link href="<?php echo $this->baseUrl();?>/public/css/summary.css" type="text/css" rel="stylesheet" media="screen"/>
   <div id="content1">       	
            	<a href="#"><img id="changebj" src="<?php echo $this->baseUrl();?>/public/images/changebj.png"/></a>
                <img id="bj" src="<?php echo $this->baseUrl();?>/public/images/summary/bj.jpg"/>
            </div><!-- end of content1 -->
            <div id="content2">
                <div id="patch1">
                	<img class="title_pic" src="<?php echo $this->baseUrl();?>/public/images/summary/department.jpg"/>
                    <img  class="b_left" src="<?php echo $this->baseUrl();?>/public/images/summary/border_sum_big.jpg"/>
                    <img  class="b_right" src="<?php echo $this->baseUrl();?>/public/images/summary/border_sum_big.jpg"/>
                    <img src="<?php echo $this->baseUrl();?>/public/images/summary/chart.jpg"/>                    
              	</div>
              <!-- end of patch1 -->
              	<div id="patch2">
                	<img class="title_pic" src="<?php echo $this->baseUrl();?>/public/images/summary/introduction.jpg"/>
                    <img  class="b_left" src="<?php echo $this->baseUrl();?>/public/images/summary/border_sum_small.jpg"/>
                    <img  class="b_right" src="<?php echo $this->baseUrl();?>/public/images/summary/border_sum_small.jpg"/>   
                    <img class="showpic" src="<?php echo $this->baseUrl();?>/public/images/summary/show1.jpg"/>
                    <div class="text">
                    	<p>华中科技大学腾讯创新俱乐部是由华中科技大学和腾讯科技（深圳）有限公司于2007年4月合作创办的以项目为核心的创新实践型高校学生社团，由华中科技大学计算机学院直接领导。俱乐部目前共有成员73名，其中研究生13名本科生60名。2009年度俱乐部成员发表论文一篇，申请到国家创新基金3项在全国13个腾讯创新俱乐部评比中获全国2009年度"最佳腾讯创新俱乐部"及"最佳技术俱乐部"称号。</p>
                    </div>             
              	</div>
              <!-- end of patch2 -->
              	<div id="patch2">
                	<img  class="title_pic" src="<?php echo $this->baseUrl();?>/public/images/summary/purpose.jpg"/>
                    <img  class="b_left" src="<?php echo $this->baseUrl();?>/public/images/summary/border_sum_small.jpg"/>
                    <img  class="b_right" src="<?php echo $this->baseUrl();?>/public/images/summary/border_sum_small.jpg"/>   
                    <img class="showpic" src="<?php echo $this->baseUrl();?>/public/images/summary/show2.jpg"/>
                    <div class="text">
                    	<p>华中科技大学腾讯创新俱乐部是由华中科技大学和腾讯科技（深圳）有限公司合作 创办的以技术为核心的创新实践型高校学生社团，由华中科技大学计算机学院直接 领导。<br/><br/>以培养技术扎实、视野宽阔、具有良好团队合作精神的人才为目标，以新颖的创意和专业的技术创造价值、服务社会</p>
                    </div>             
              	</div>
              <!-- end of patch3 -->
            </div><!-- end of content1 -->